# Generated by Django 3.1.2 on 2020-11-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('anio', models.DateTimeField(auto_now=True)),
                ('cliente_nombre', models.CharField(max_length=220)),
                ('cliente_direccion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=220)),
                ('precio_unitario', models.FloatField()),
                ('unidades', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
            ],
        ),
    ]
